name: Workflow
on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Before script
        run: cmake .

      - name: Build
        run: cmake --build .
